name: Terraform Quality & Security

on:
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
            directory: infra/
            soft_fail: true 

      - name: Terraform Validate
        run: terraform validate